title: Brice Banda
url: "https://bricebanda.com/"
baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "This website is built using a base created by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Arts and Letters"
   link: "https://bricebanda.com/artletter/"
 - name: "Science"
   link: "https://bricebanda.com/science/"
 - name: "Extraneous"
   link: "https://bricebanda.com/extraneous/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "https://bricebanda.com/contact/"
