title: Brice Banda
url: "https://bricebanda.com"
baseurl: "/about"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "This website is built using a base created by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/about/"
 - name: "Arts"
   link: "https://bricebanda.com/arts/"
 - name: "Letters"
   link: "https://bricebanda.com/letters/
 - name: "Extraneous"
   link: "https://bricebanda.com/extraneous/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "https://bricebanda.com/contact/"
